// src/schema/thirdPartySchema.ts
import type { PatchObject } from './patchSchema.js';

/**
 * Represents a third-party package update
 */
export interface ThirdPartyUpdate {
  /** Package name */
  name: string;
  /** Current version in package.json */
  currentVersion: string;
  /** Latest available version based on update strategy */
  latestVersion: string;
  /** Type of update (patch, minor, or major) */
  updateType: 'patch' | 'minor' | 'major';
  /** Whether this is a devDependency */
  isDevDependency: boolean;
  /** If the update was skipped */
  skipped?: boolean;
  /** Reason for skipping */
  skipReason?: string;
}

/**
 * Report for third-party dependency updates
 */
export interface ThirdPartyReport {
  /** Number of packages eligible for update */
  eligiblePackages: number;
  /** Total number of packages in package.json */
  totalPackages: number;
  /** Updates that were applied */
  updates: ThirdPartyUpdate[];
  /** Updates that were skipped (e.g., risky major updates) */
  skipped: ThirdPartyUpdate[];
  /** Patches generated for updates */
  patches: PatchObject[];
  /** Build errors after updates */
  buildErrors?: string[];
  /** Patches generated by Claude to fix breaking changes */
  claudeFixes?: PatchObject[];
  /** Whether the final build succeeded */
  finalBuildSuccess: boolean;
  /** Final build errors if any */
  finalBuildErrors?: string[];
}

/**
 * Configuration for third-party updates
 */
interface ThirdPartyConfig {
  /** Update strategy for dependencies */
  updateDeps: 'none' | 'patch' | 'minor' | 'major';
  /** Update strategy for devDependencies */
  updateDevDeps: 'none' | 'patch' | 'minor' | 'major';
  /** Whether to clean node_modules after updates */
  cleanInstall: boolean;
  /** Whether to use Claude to fix breaking changes */
  fixErrors: boolean;
}